// flow-typed signature: 766a348b97c4bf00fb1b51a3e817920a
// flow-typed version: <<STUB>>/react-dazzle_v^1.4.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dazzle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dazzle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dazzle/dist/lib' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/AddWidget' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/Column' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/Dashboard' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/DefaultFrame' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/ItemTypes' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/LayoutRenderer' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/Row' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/WidgetFrame' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/components/Widgets' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/index' {
  declare module.exports: any;
}

declare module 'react-dazzle/lib/util/index' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/AddWidgetDialog' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/app' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/Container' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/CustomAddWidgetButton' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/EditBar' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/Header' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/widgets/AnotherWidget/index' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/components/widgets/HelloWorld/Index' {
  declare module.exports: any;
}

declare module 'react-dazzle/sample/index' {
  declare module.exports: any;
}

declare module 'react-dazzle/server/node-app-server' {
  declare module.exports: any;
}

declare module 'react-dazzle/server/node-proxy' {
  declare module.exports: any;
}

declare module 'react-dazzle/server/node-server' {
  declare module.exports: any;
}

declare module 'react-dazzle/server/proxy-config' {
  declare module.exports: any;
}

declare module 'react-dazzle/server/webpack-dev-proxy' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/AddWidget.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/Column.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/Dashboard.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/Row.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/WidgetFrame.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/components/Widgets.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/entry' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/fake/ContainerWithDndContext' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/fake/TestComponent' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/fake/TestCustomFrame' {
  declare module.exports: any;
}

declare module 'react-dazzle/test/util/until.spec' {
  declare module.exports: any;
}

declare module 'react-dazzle/webpack.config' {
  declare module.exports: any;
}

declare module 'react-dazzle/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dazzle/dist/lib.js' {
  declare module.exports: $Exports<'react-dazzle/dist/lib'>;
}
declare module 'react-dazzle/lib/components/AddWidget.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/AddWidget'>;
}
declare module 'react-dazzle/lib/components/Column.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/Column'>;
}
declare module 'react-dazzle/lib/components/Dashboard.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/Dashboard'>;
}
declare module 'react-dazzle/lib/components/DefaultFrame.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/DefaultFrame'>;
}
declare module 'react-dazzle/lib/components/ItemTypes.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/ItemTypes'>;
}
declare module 'react-dazzle/lib/components/LayoutRenderer.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/LayoutRenderer'>;
}
declare module 'react-dazzle/lib/components/Row.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/Row'>;
}
declare module 'react-dazzle/lib/components/WidgetFrame.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/WidgetFrame'>;
}
declare module 'react-dazzle/lib/components/Widgets.js' {
  declare module.exports: $Exports<'react-dazzle/lib/components/Widgets'>;
}
declare module 'react-dazzle/lib/index.js' {
  declare module.exports: $Exports<'react-dazzle/lib/index'>;
}
declare module 'react-dazzle/lib/util/index.js' {
  declare module.exports: $Exports<'react-dazzle/lib/util/index'>;
}
declare module 'react-dazzle/sample/components/AddWidgetDialog.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/AddWidgetDialog'>;
}
declare module 'react-dazzle/sample/components/app.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/app'>;
}
declare module 'react-dazzle/sample/components/Container.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/Container'>;
}
declare module 'react-dazzle/sample/components/CustomAddWidgetButton.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/CustomAddWidgetButton'>;
}
declare module 'react-dazzle/sample/components/EditBar.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/EditBar'>;
}
declare module 'react-dazzle/sample/components/Header.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/Header'>;
}
declare module 'react-dazzle/sample/components/widgets/AnotherWidget/index.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/widgets/AnotherWidget/index'>;
}
declare module 'react-dazzle/sample/components/widgets/HelloWorld/Index.jsx' {
  declare module.exports: $Exports<'react-dazzle/sample/components/widgets/HelloWorld/Index'>;
}
declare module 'react-dazzle/sample/index.js' {
  declare module.exports: $Exports<'react-dazzle/sample/index'>;
}
declare module 'react-dazzle/server/node-app-server.js' {
  declare module.exports: $Exports<'react-dazzle/server/node-app-server'>;
}
declare module 'react-dazzle/server/node-proxy.js' {
  declare module.exports: $Exports<'react-dazzle/server/node-proxy'>;
}
declare module 'react-dazzle/server/node-server.js' {
  declare module.exports: $Exports<'react-dazzle/server/node-server'>;
}
declare module 'react-dazzle/server/proxy-config.js' {
  declare module.exports: $Exports<'react-dazzle/server/proxy-config'>;
}
declare module 'react-dazzle/server/webpack-dev-proxy.js' {
  declare module.exports: $Exports<'react-dazzle/server/webpack-dev-proxy'>;
}
declare module 'react-dazzle/test/components/AddWidget.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/AddWidget.spec'>;
}
declare module 'react-dazzle/test/components/Column.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/Column.spec'>;
}
declare module 'react-dazzle/test/components/Dashboard.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/Dashboard.spec'>;
}
declare module 'react-dazzle/test/components/Row.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/Row.spec'>;
}
declare module 'react-dazzle/test/components/WidgetFrame.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/WidgetFrame.spec'>;
}
declare module 'react-dazzle/test/components/Widgets.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/components/Widgets.spec'>;
}
declare module 'react-dazzle/test/entry.js' {
  declare module.exports: $Exports<'react-dazzle/test/entry'>;
}
declare module 'react-dazzle/test/fake/ContainerWithDndContext.jsx' {
  declare module.exports: $Exports<'react-dazzle/test/fake/ContainerWithDndContext'>;
}
declare module 'react-dazzle/test/fake/TestComponent.jsx' {
  declare module.exports: $Exports<'react-dazzle/test/fake/TestComponent'>;
}
declare module 'react-dazzle/test/fake/TestCustomFrame.jsx' {
  declare module.exports: $Exports<'react-dazzle/test/fake/TestCustomFrame'>;
}
declare module 'react-dazzle/test/util/until.spec.js' {
  declare module.exports: $Exports<'react-dazzle/test/util/until.spec'>;
}
declare module 'react-dazzle/webpack.config.js' {
  declare module.exports: $Exports<'react-dazzle/webpack.config'>;
}
declare module 'react-dazzle/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-dazzle/webpack.config.prod'>;
}
