// flow-typed signature: 81877bd210272f7bcd30873ad79b9956
// flow-typed version: <<STUB>>/swagger-ui_v^3.20.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-ui/dist/swagger-ui-standalone-preset' {
  declare module.exports: any;
}

declare module 'swagger-ui/dist/swagger-ui' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-ui/dist/swagger-ui-standalone-preset.js' {
  declare module.exports: $Exports<'swagger-ui/dist/swagger-ui-standalone-preset'>;
}
declare module 'swagger-ui/dist/swagger-ui.js' {
  declare module.exports: $Exports<'swagger-ui/dist/swagger-ui'>;
}
