# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Configuration(Model):
	"""NOTE: This class is auto generated by the swagger code generator program.

	Do not edit the class manually.
	"""

	def __init__(self, id: int=None, name: str=None, dataset_id: int=None, model_id: int=None):  # noqa: E501
		"""Configuration - a model defined in Swagger

		:param id: The id of this Configuration.  # noqa: E501
		:type id: int
		:param name: The name of this Configuration.  # noqa: E501
		:type name: str
		:param dataset_id: The dataset_id of this Configuration.  # noqa: E501
		:type dataset_id: int
		:param model_id: The model_id of this Configuration.  # noqa: E501
		:type model_id: int
		"""
		self.swagger_types = {
			'id': int,
			'name': str,
			'dataset_id': int,
			'model_id': int
		}

		self.attribute_map = {
			'id': 'id',
			'name': 'name',
			'dataset_id': 'dataset_id',
			'model_id': 'model_id'
		}

		self._id = id
		self._name = name
		self._dataset_id = dataset_id
		self._model_id = model_id

	@classmethod
	def from_dict(cls, dikt) -> 'Configuration':
		"""Returns the dict as a model

		:param dikt: A dict.
		:type: dict
		:return: The configuration of this Configuration.  # noqa: E501
		:rtype: Configuration
		"""
		return util.deserialize_model(dikt, cls)

	@property
	def id(self) -> int:
		"""Gets the id of this Configuration.


		:return: The id of this Configuration.
		:rtype: int
		"""
		return self._id

	@id.setter
	def id(self, id: int):
		"""Sets the id of this Configuration.


		:param id: The id of this Configuration.
		:type id: int
		"""

		self._id = id

	@property
	def name(self) -> str:
		"""Gets the name of this Configuration.


		:return: The name of this Configuration.
		:rtype: str
		"""
		return self._name

	@name.setter
	def name(self, name: str):
		"""Sets the name of this Configuration.


		:param name: The name of this Configuration.
		:type name: str
		"""

		self._name = name

	@property
	def dataset_id(self) -> int:
		"""Gets the dataset_id of this Configuration.


		:return: The dataset_id of this Configuration.
		:rtype: int
		"""
		return self._dataset_id

	@dataset_id.setter
	def dataset_id(self, dataset_id: int):
		"""Sets the dataset_id of this Configuration.


		:param dataset_id: The dataset_id of this Configuration.
		:type dataset_id: int
		"""

		self._dataset_id = dataset_id

	@property
	def model_id(self) -> int:
		"""Gets the model_id of this Configuration.


		:return: The model_id of this Configuration.
		:rtype: int
		"""
		return self._model_id

	@model_id.setter
	def model_id(self, model_id: int):
		"""Sets the model_id of this Configuration.


		:param model_id: The model_id of this Configuration.
		:type model_id: int
		"""

		self._model_id = model_id
