# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Train(Model):
	"""NOTE: This class is auto generated by the swagger code generator program.

	Do not edit the class manually.
	"""

	def __init__(self, id: int=None, dataset_id: int=None, model_id: int=None):  # noqa: E501
		"""Train - a model defined in Swagger

		:param id: The id of this Train.  # noqa: E501
		:type id: int
		:param dataset_id: The dataset_id of this Train.  # noqa: E501
		:type dataset_id: int
		:param model_id: The model_id of this Train.  # noqa: E501
		:type model_id: int
		"""
		self.swagger_types = {
			'id': int,
			'dataset_id': int,
			'model_id': int
		}

		self.attribute_map = {
			'id': 'id',
			'dataset_id': 'dataset_id',
			'model_id': 'model_id'
		}

		self._id = id
		self._dataset_id = dataset_id
		self._model_id = model_id

	@classmethod
	def from_dict(cls, dikt) -> 'Train':
		"""Returns the dict as a model

		:param dikt: A dict.
		:type: dict
		:return: The train of this Train.  # noqa: E501
		:rtype: Train
		"""
		return util.deserialize_model(dikt, cls)

	@property
	def id(self) -> int:
		"""Gets the id of this Train.


		:return: The id of this Train.
		:rtype: int
		"""
		return self._id

	@id.setter
	def id(self, id: int):
		"""Sets the id of this Train.


		:param id: The id of this Train.
		:type id: int
		"""

		self._id = id

	@property
	def dataset_id(self) -> int:
		"""Gets the dataset_id of this Train.


		:return: The dataset_id of this Train.
		:rtype: int
		"""
		return self._dataset_id

	@dataset_id.setter
	def dataset_id(self, dataset_id: int):
		"""Sets the dataset_id of this Train.


		:param dataset_id: The dataset_id of this Train.
		:type dataset_id: int
		"""

		self._dataset_id = dataset_id

	@property
	def model_id(self) -> int:
		"""Gets the model_id of this Train.


		:return: The model_id of this Train.
		:rtype: int
		"""
		return self._model_id

	@model_id.setter
	def model_id(self, model_id: int):
		"""Sets the model_id of this Train.


		:param model_id: The model_id of this Train.
		:type model_id: int
		"""

		self._model_id = model_id
